image: maven:latest

stages:
  - build
  - package

cache:
  paths:
    - .m2/repository/
    - target/

build:
  script:
    - mvn compile
  only:
    - merge_requests
  when: always

package:
  script:
    - mvn package
  only:
    - merge_requests
  when: always
  artifacts:
    paths:
      - target/colonisation_prunier_rabotin_sechi_servat-1.0.jar